logo:
  title: ''
  image: ''

# copy to _config.yml in the root to enable syntax highlighting
syntax_highlighter: prismjs
prismjs:
  preprocess: false
  line_number: true
  line_threshold: 0
  tab_replace: ''
