# common config
title: hexo-bootstrap-theme
subtitle: ''
description: This is a bootstrap theme for hexo.

# theme config
share_image: ''
logo:
  title: ''
  image: ''
footer_content: ''

# copy to root _config.yml to enable syntax highlighting
syntax_highlighter: prismjs
prismjs:
  preprocess: false
  line_number: true
  line_threshold: 0
  tab_replace: ''
